# requests.rest (from REST CLient extention on VScode)
GET http://localhost:3000/users

###
POST http://localhost:3000/users
Content-Type: application/json

{"username": "Mariam", "password": "wordpass"}

###
GET http://localhost:3000/users/68d5d03f3488c3846bc01495/posts

###
POST http://localhost:3000/login
Content-Type: application/json

{"username": "said", "password": "tresbien"}


###

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3lsZSIsImlhdCI6MTc1ODgzNzQ1MywiZXhwIjoxNzU4ODM3NDgzfQ.ADgUke6VKXYvaYHq39Kfoq4sDsHrXLsfbvgxvObc7qc


###
POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3lsZSIsImlhdCI6MTc1ODgzNzQxMX0.Z_8PBGoLr-bPtcqWq82xs_9UbxQgStQWiY7093eRnIY"
    }


###
DELETE http://localhost:3000/logout
Content-Type: application/json

{"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3lsZSIsImlhdCI6MTc1ODgzNzQxMX0.Z_8PBGoLr-bPtcqWq82xs_9UbxQgStQWiY7093eRnIY"}